on:
  push:
    branches:
      - main  # ודא שזה אכן שם הבראנץ' שלך

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Yiska-server
            git pull origin main
            npm install
            sudo systemctl stop my_node_app.service
            sudo systemctl start my_node_app.service
            sudo systemctl status my_node_app.service
