name: Deploy to EC2 server
on:
  push:
    branches:
      - main # או 'main', תלוי בשם הבראנץ' הראשי שלך

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 server
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER || 'ubuntu' }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Yiska-server
          git pull origin main
          sudo systemctl stop my_node_app.service
          sudo systemctl restart my_node_app.service
          sudo systemctl start my_node_app.service
          sudo systemctl status my_node_app.service
